# Generated by Django 5.0.2 on 2024-03-26 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venues', '0017_alter_savedplaces_user_alter_uservisits_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('timing', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='EventPics/')),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='CastImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_image', models.ImageField(blank=True, null=True, upload_to='CastImage/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_image', to='Venues.events')),
            ],
            options={
                'db_table': 'cast_images',
            },
        ),
    ]
